/**
 * Parole che possono essere scelte come SOLUZIONE (lista ufficiale delle
 * risposte di Wordle: 2.315 parole comuni di cinque lettere). È un
 * sottoinsieme di VALID_WORDS.
 * Fonte: https://gist.github.com/cfreshman (wordle-answers-alphabetical).
 *
 * Divise per il livello CEFR a cui ci si aspetta che uno studente d'inglese
 * conosca la parola — la scala dei corsi di lingua — così la difficoltà del
 * gioco può crescere col livello invece di dipendere solo dal timer.
 *
 * I livelli stanno in scripts/cefr-levels.json e vengono accorpati a fasce da
 * questo generatore. NON si usa il campo `level` del dizionario: quello dice
 * quanto una parola è comune per un madrelingua, che per chi impara è un'altra
 * domanda (fra le sue "comuni" ci sono lease, merge e grasp).
 *
 * File di dati generato — non modificare a mano.
 * Si rigenera con: node scripts/build-answer-tiers.mjs
 */

/** Parole dei primi due livelli di corso: le sa chiunque abbia cominciato. */
export const A1_A2_WORDS: readonly string[] = [
  "about","above","actor","adult","after","again","agent","agree","ahead","alarm",
  "album","alive","allow","alone","along","among","angel","anger","angle","angry",
  "ankle","annoy","apart","apple","apply","argue","arrow","audio","aunty","awake",
  "award","awful","bacon","badly","baker","basic","beach","beard","began","begin",
  "begun","being","below","bench","berry","birth","black","blind","block","blood",
  "bluer","board","brain","bread","break","brick","bring","broke","brown","brush",
  "build","built","bunch","bunny","camel","candy","carry","catch","cause","chain",
  "chair","cheap","check","chess","chest","child","china","chose","class","clean",
  "clear","click","climb","clock","close","cloth","cloud","coach","color","couch",
  "cough","could","count","cover","crash","crazy","cream","cried","crime","cross",
  "crowd","curry","cycle","daddy","daily","dairy","dance","death","diary","dirty",
  "doing","dozen","drank","dream","dress","dried","drink","drive","drove","dutch",
  "early","earth","eaten","eight","elbow","email","empty","enemy","enjoy","enter",
  "entry","equal","error","essay","event","every","exact","extra","fairy","false",
  "favor","fence","ferry","fever","fewer","field","fifth","fifty","fight","final",
  "first","flood","floor","flour","flown","forty","found","fresh","fried","front",
  "froze","fruit","funny","ghost","giant","given","glass","glove","going","grade",
  "grape","grass","great","green","greet","group","grown","guard","guess","guest",
  "guide","habit","happy","heard","heart","heavy","hello","hippo","hobby","honey",
  "horse","hotel","house","human","hurry","image","jelly","judge","juice","knife",
  "knock","known","koala","label","large","later","laugh","learn","least","leave",
  "lemon","level","light","limit","local","login","lorry","lower","lucky","lunch",
  "lying","magic","mango","marry","match","maybe","meant","melon","metal","meter",
  "might","minus","model","money","month","motor","mouse","mouth","movie","mummy",
  "music","never","newer","nicer","niece","night","ninth","noise","noisy","north",
  "novel","nurse","ocean","offer","often","older","olive","onion","order","other",
  "owner","paint","paper","party","pasta","peace","peach","penny","phone","photo",
  "piano","piece","pilot","pizza","place","plane","plant","plate","point","pound",
  "power","press","price","print","prize","proud","pupil","puppy","purse","queen",
  "queue","quick","quiet","quite","radio","rainy","raise","reach","ready","relax",
  "reply","rider","right","river","robot","round","ruder","ruler","safer","salad",
  "sauce","scarf","scary","score","sense","serve","seven","shake","shall","shape",
  "share","shark","sharp","sheep","sheet","shelf","shine","shirt","shook","shoot",
  "short","shout","shown","silly","since","sixth","sixty","skate","skill","skirt",
  "sleep","slept","slice","small","smart","smell","smile","smoke","snack","snake",
  "solve","sorry","sound","south","space","speak","speed","spell","spend","spent",
  "spoke","spoon","sport","staff","stage","stair","stamp","stand","start","state",
  "steak","steal","stick","still","stole","stone","stood","store","storm","story",
  "stove","study","stuff","style","sugar","sunny","super","surer","sushi","sweet",
  "table","taken","taste","tasty","teach","teddy","teeth","tenth","thank","their",
  "there","these","thick","thing","think","third","those","three","threw","throw",
  "thumb","tiger","tight","title","toast","today","tooth","topic","total","touch",
  "towel","tower","track","train","trash","treat","trick","tried","truck","truer",
  "truth","tulip","tweet","twice","tying","uncle","under","until","upper","upset",
  "using","usual","value","video","visit","vodka","voice","waste","watch","water",
  "weigh","welsh","whale","wheel","where","which","while","white","whole","whose",
  "wider","windy","woman","women","world","worry","worse","worst","would","write",
  "wrong","wrote","young","zebra",
];

/** Vocabolario da studente intermedio. */
export const B1_WORDS: readonly string[] = [
  "adapt","admin","admit","adopt","aging","alert","alien","alike","alley","aloud",
  "amaze","amuse","anime","apron","arena","armor","aside","attic","avoid","aware",
  "awoke","badge","bagel","basil","basis","bathe","beast","belly","bible","bingo",
  "blade","blame","blank","bleed","blond","blown","bonus","booth","boxer","brake",
  "brand","brave","bride","brief","broad","broom","buddy","bully","burnt","buyer",
  "cabin","cable","canal","canoe","cello","chalk","chart","chase","cheat","cheek",
  "cheer","chick","chief","chili","chill","choir","cigar","claim","clerk","cliff",
  "clown","coast","cocoa","comic","comma","court","crack","craft","crawl","crown",
  "cruel","curly","curve","daisy","dealt","delay","depth","digit","disco","diver",
  "dizzy","donut","doubt","draft","drama","drawn","drier","drill","drown","drunk",
  "dryer","dusty","dying","eagle","eater","elect","erase","exist","faith","fancy",
  "fault","fetch","fiber","fibre","finer","flame","flash","float","flute","flyer",
  "focus","foggy","force","frame","freed","frost","fully","gamer","gayer","geese",
  "globe","goose","grain","grand","graph","grave","grill","hairy","handy","hilly",
  "honor","humid","humor","ideal","idiot","igloo","inbox","index","inner","input",
  "intro","issue","jewel","joint","juicy","kayak","kebab","labor","latte","layer",
  "legal","liver","logic","loose","loser","lover","lyric","madam","major","maker",
  "mamma","march","mayor","medal","media","merry","metro","miner","minor","moist",
  "moral","motel","muddy","nanny","nasty","newly","ninja","occur","odder","opera",
  "organ","ought","paler","panic","paste","pause","pearl","pence","petal","plain",
  "polar","porch","pride","proof","prove","punch","purer","quote","racer","ranch",
  "range","rapid","rarer","razor","react","refer","renew","repay","reset","retry",
  "reuse","rhino","rhyme","rifle","riper","risen","risky","roast","rough","route",
  "royal","rugby","sadly","salty","sandy","sauna","scale","scare","scene","screw",
  "scuba","shade","shame","shave","shell","shift","shiny","shock","shone","shore",
  "sight","skier","slave","slide","slope","snail","snowy","solar","solid","spare",
  "spice","spicy","spill","spite","split","spoil","spray","stack","stare","steam",
  "steel","steep","sting","stink","stock","stool","straw","stuck","stung","swear",
  "sweat","sweep","swept","swing","sword","swore","swung","syrup","tense","theft",
  "theme","thief","timer","torch","tough","trade","trail","trend","trial","tribe",
  "trout","truly","trunk","trust","tutor","twist","undid","union","unite","untie",
  "unzip","urban","valid","vegan","verse","villa","virus","voter","vowel","wagon",
  "waist","weird","wheat","widow","width","wiser","witch","woken","worth","wound",
  "wrist","yacht","youth",
];

/** Intermedio avanzato: si incontrano leggendo, non a tavola. */
export const B2_WORDS: readonly string[] = [
  "abbey","abort","abuse","acorn","acute","adore","agile","agony","aisle","algae",
  "align","alpha","altar","alter","amber","amend","ample","arise","aroma","arose",
  "array","asset","audit","await","baggy","banjo","baron","basin","batch","bicep",
  "binge","bison","bland","blast","blaze","blend","bless","blink","bloom","blunt",
  "blush","boast","boney","boost","bossy","bound","brace","braid","brass","bravo",
  "breed","bribe","brisk","brook","broth","buggy","bulky","burst","bused","cacti",
  "cargo","carol","carve","cater","cease","champ","chant","chaos","charm","chirp",
  "choke","chord","chore","chuck","chunk","cider","civic","civil","clash","cling",
  "cloak","clone","clung","cobra","colon","comet","comfy","coral","cramp","crane",
  "crate","creek","creep","crept","crisp","crude","crumb","crush","crust","cubic",
  "curse","curvy","cyber","debit","debug","debut","decay","decor","delta","demon",
  "denim","dense","depot","devil","dimly","diner","ditch","dodge","dolly","donor",
  "dough","drain","dread","drift","drone","dummy","duvet","dwarf","eager","elder",
  "elite","equip","erect","erupt","ethic","fable","faint","fatal","fatty","feast",
  "fizzy","flake","flare","flask","fleet","flesh","flick","flier","flirt","flock",
  "fluid","flush","forge","forth","forum","frank","fraud","freak","freer","frown",
  "fungi","furry","fuzzy","genie","genre","girly","giver","glide","glory","grace",
  "grant","grasp","gravy","greed","grief","grind","groan","groom","gross","growl",
  "guilt","gypsy","halve","harsh","hatch","hater","haunt","hedge","hence","hunch",
  "husky","hyena","hyper","icing","idiom","imply","irony","itchy","ivory","joker",
  "jolly","jumbo","khaki","kiosk","kitty","kneel","knelt","lager","lance","larva",
  "leafy","leaky","leant","leapt","lease","leash","lever","linen","liner","llama",
  "lobby","lodge","loyal","lunar","madly","mafia","maize","manga","manly","maple",
  "marsh","medic","mercy","merge","merit","micro","milky","mocha","modem","moldy",
  "moody","moose","motto","mound","mount","mourn","mover","mower","munch","naive",
  "naval","needy","nerdy","nerve","noble","nylon","obese","oddly","orbit","ounce",
  "outer","owing","oxide","ozone","panel","patch","patio","pedal","pesto","petty",
  "phase","picky","piggy","pinch","pinky","pitch","pixel","plank","plaza","plead",
  "plump","poker","poppy","pouch","prank","prawn","prick","prime","prior","puffy",
  "pulse","quack","quake","quart","queer","query","quest","quilt","radar","rally",
  "ramen","ratio","raven","realm","rebel","recap","recur","rehab","reign","relay",
  "rerun","retro","ridge","rigid","rinse","ripen","rival","robin","rocky","rumor",
  "rural","rusty","saint","salon","salsa","saner","scent","scoop","scope","scout",
  "scrap","scrub","sedan","seize","setup","shady","shaft","shaky","sheer","shove",
  "shrub","shrug","shyly","siege","silky","siren","skull","slack","slang","slash",
  "slate","smash","smoky","sneak","sniff","snore","snuck","soapy","sober","spade",
  "spark","spear","spelt","sperm","spied","spike","spilt","spine","squad","stain",
  "stake","stale","stalk","stall","stank","steer","stern","stiff","stony","strap",
  "stray","strip","stunk","suing","suite","swamp","swell","swift","sworn","taker",
  "tango","tease","tempo","thigh","tidal","timid","token","tonic","toxic","trace",
  "tramp","tread","troll","troop","trump","tumor","turbo","twirl","ulcer","ultra",
  "uncut","unfit","unify","unity","urine","usage","utter","vague","valve","vapor",
  "vault","venom","venue","verge","vinyl","viola","viral","vital","vivid","vocal",
  "voila","vomit","waltz","weary","weave","wedge","whine","whirl","whisk","widen",
  "witty","woody","woven","wreck","yeast","yield",
];

/** Parole avanzate, letterarie o tecniche: quelle che si imparano giocando. */
export const C1_C2_WORDS: readonly string[] = [
  "aback","abase","abate","abbot","abhor","abide","abled","abode","abyss","acrid",
  "adage","adept","adobe","adorn","affix","afire","afoot","afoul","agape","agate",
  "aglow","agora","aider","alibi","allay","allot","alloy","aloft","aloof","amass",
  "amble","amiss","amity","amply","angst","annex","annul","anode","antic","anvil",
  "aorta","aphid","aping","apnea","aptly","arbor","ardor","arson","artsy","ascot",
  "ashen","askew","assay","atoll","atone","augur","avail","avert","avian","awash",
  "axial","axiom","axion","azure","baler","balmy","banal","barge","basal","baste",
  "baton","batty","bawdy","bayou","beady","beech","beefy","befit","begat","beget",
  "belch","belie","belle","beret","berth","beset","betel","bevel","bezel","biddy",
  "bigot","bilge","billy","biome","birch","bitty","blare","bleak","bleat","bleep",
  "blimp","bliss","blitz","bloat","bloke","bluff","blurb","blurt","bobby","bongo",
  "booby","booty","booze","boozy","borax","borne","bosom","botch","bough","boule",
  "bowel","brash","brawl","brawn","briar","brine","brink","briny","broil","brood",
  "brunt","brute","budge","bugle","bulge","burly","bushy","butch","butte","buxom",
  "bylaw","cabal","cabby","cacao","cache","caddy","cadet","cagey","cairn","cameo",
  "canny","canon","caper","caput","carat","caste","catty","caulk","cavil","cedar",
  "chafe","chaff","chard","chasm","chide","chime","chock","chump","churn","chute",
  "cinch","circa","clack","clamp","clang","clank","clasp","cleat","cleft","clink",
  "clout","clove","cluck","clued","clump","conch","condo","conic","copse","corer",
  "corny","coupe","coven","covet","covey","cower","coyly","crank","crass","crave",
  "craze","creak","credo","creed","creme","crepe","cress","crest","crick","crier",
  "crimp","croak","crock","crone","crony","crook","croup","crump","crypt","cumin",
  "curio","cutie","cynic","dally","dandy","datum","daunt","debar","decal","decoy",
  "decry","defer","deign","deity","delve","demur","derby","deter","detox","deuce",
  "dicey","dilly","dingo","dingy","diode","dirge","ditto","ditty","dodgy","dogma",
  "dopey","dowdy","dowel","downy","dowry","drake","drape","drawl","droit","droll",
  "drool","droop","dross","druid","dryly","duchy","dully","dumpy","dunce","dusky",
  "dwell","dwelt","easel","ebony","eclat","edict","edify","eerie","egret","eject",
  "eking","elate","elegy","elfin","elide","elope","elude","embed","ember","emcee",
  "enact","endow","enema","ennui","ensue","envoy","epoch","epoxy","erode","ester",
  "ether","ethos","etude","evade","evict","evoke","exalt","excel","exert","exile",
  "expel","extol","exult","eying","facet","fanny","farce","fauna","fecal","feign",
  "fella","felon","femme","femur","feral","fetal","fetid","fetus","ficus","fiend",
  "fiery","filer","filet","filly","filmy","filth","finch","fishy","fixer","fjord",
  "flack","flail","flair","flaky","flank","fleck","fling","flint","flora","floss",
  "flout","fluff","fluke","flume","flung","flunk","foamy","focal","foist","folio",
  "folly","foray","forgo","forte","foyer","frail","friar","frill","frisk","fritz",
  "frock","frond","froth","fudge","fugue","funky","furor","fussy","gaffe","gaily",
  "gamma","gamut","gassy","gaudy","gauge","gaunt","gauze","gavel","gawky","gayly",
  "gazer","gecko","geeky","ghoul","giddy","gipsy","girth","glade","gland","glare",
  "glaze","gleam","glean","glint","gloat","gloom","gloss","glyph","gnash","gnome",
  "godly","golem","golly","gonad","goner","goody","gooey","goofy","gorge","gouge",
  "gourd","graft","grail","grate","graze","grime","grimy","gripe","groin","grope",
  "grout","grove","gruel","gruff","grunt","guava","guild","guile","guise","gulch",
  "gully","gumbo","gummy","guppy","gusto","gusty","hardy","harem","harpy","harry",
  "haste","hasty","haute","haven","havoc","hazel","heady","heath","heave","hefty",
  "heist","helix","heron","hinge","hippy","hitch","hoard","hoist","holly","homer",
  "horde","horny","hotly","hound","hovel","hover","howdy","humph","humus","hunky",
  "hussy","hutch","hydro","hymen","icily","idler","idyll","iliac","imbue","impel",
  "inane","incur","inept","inert","infer","ingot","inlay","inlet","inter","ionic",
  "irate","islet","jaunt","jazzy","jerky","jetty","jiffy","joist","joust","jumpy",
  "junta","junto","juror","kappa","karma","kinky","knack","knave","knead","kneed",
  "knoll","krill","laden","ladle","lanky","lapel","lapse","lasso","latch","lathe",
  "leach","ledge","leech","leery","lefty","leggy","lemur","leper","libel","liege",
  "liken","lilac","limbo","lingo","lipid","lithe","livid","loamy","loath","locus",
  "lofty","loopy","louse","lousy","lowly","lucid","lumen","lumpy","lunge","lupus",
  "lurch","lurid","lusty","lymph","lynch","macaw","macho","macro","magma","mambo",
  "mammy","mange","mangy","mania","manic","manor","mason","masse","matey","mauve",
  "maxim","mealy","meaty","mecca","melee","midge","midst","mimic","mince","minim",
  "minty","mirth","miser","missy","modal","mogul","molar","moron","morph","mossy",
  "motif","moult","mucky","mucus","mulch","mural","murky","mushy","musky","musty",
  "myrrh","nadir","nasal","natal","navel","neigh","niche","ninny","nobly","nomad",
  "noose","nosey","notch","nudge","nutty","nymph","oaken","octal","octet","offal",
  "olden","ombre","omega","onset","opine","opium","optic","otter","outdo","outgo",
  "ovary","ovate","overt","ovine","ovoid","paddy","pagan","palsy","pansy","papal",
  "parer","parka","parry","parse","pasty","patsy","patty","payee","payer","pecan",
  "penal","penne","perch","peril","perky","pesky","phony","piety","piney","pinto",
  "piper","pique","pithy","pivot","pixie","plaid","plait","pleat","plied","plier",
  "pluck","plumb","plume","plunk","plush","poesy","poise","polka","polyp","pooch",
  "poser","posit","posse","pouty","preen","pried","primo","prism","privy","probe",
  "prone","prong","prose","prowl","proxy","prude","prune","psalm","pubic","pudgy",
  "pulpy","pupal","puree","purge","pushy","putty","pygmy","quail","qualm","quark",
  "quash","quasi","quell","quill","quirk","quota","quoth","rabbi","rabid","radii",
  "rajah","ralph","randy","raspy","ratty","rayon","rearm","rebar","rebus","rebut",
  "recut","reedy","refit","regal","relic","remit","renal","repel","resin","retch",
  "revel","revue","rigor","riser","rivet","roach","rodeo","roger","rogue","roomy",
  "roost","rotor","rouge","rouse","rover","rowdy","rower","ruddy","rumba","rupee",
  "sally","salve","salvo","sappy","sassy","satin","satyr","saucy","saute","savor",
  "savoy","savvy","scald","scalp","scaly","scamp","scant","scion","scoff","scold",
  "scone","scorn","scour","scowl","scram","scree","scrum","seedy","segue","semen",
  "sepia","serif","serum","sever","sewer","shack","shale","shalt","shank","shard",
  "shawl","shear","sheen","sheik","shied","shire","shirk","shoal","shorn","showy",
  "shrew","shuck","shunt","shush","sieve","sigma","sinew","singe","sissy","skiff",
  "skimp","skulk","skunk","slain","slant","sleek","sleet","slick","slime","slimy",
  "sling","slink","sloop","slosh","sloth","slump","slung","slunk","slurp","slush",
  "slyly","smack","smear","smelt","smirk","smite","smith","smock","smote","snaky",
  "snare","snarl","sneer","snide","snipe","snoop","snort","snout","snuff","soggy",
  "sonar","sonic","sooth","sooty","sower","spank","spasm","spawn","speck","spiel",
  "spiky","spiny","spire","splat","spoof","spook","spool","spore","spout","spree",
  "sprig","spunk","spurn","spurt","squat","squib","staid","stark","stash","stave",
  "stead","steed","stein","stilt","stint","stoic","stoke","stomp","stoop","stork",
  "stout","strut","stump","stunt","suave","sulky","sully","sumac","surge","surly",
  "swami","swarm","swash","swath","swill","swine","swirl","swish","swoon","swoop",
  "synod","tabby","taboo","tacit","tacky","taffy","taint","tally","talon","tamer",
  "tangy","taper","tapir","tardy","tarot","tatty","taunt","tawny","teary","tenet",
  "tenor","tepee","tepid","terra","terse","testy","theta","thong","thorn","throb",
  "thrum","thump","thyme","tiara","tibia","tilde","tipsy","titan","tithe","toddy",
  "tonal","tonga","topaz","torso","torus","totem","toxin","tract","trait","trawl",
  "triad","trice","tripe","trite","trope","trove","truce","truss","tryst","tubal",
  "tuber","tulle","tunic","twang","tweak","tweed","twine","twixt","udder","umbra",
  "undue","unfed","unlit","unmet","unset","unwed","usher","usurp","utile","valet",
  "valor","vapid","vaunt","verso","verve","vicar","vigil","vigor","viper","visor",
  "vista","vixen","vogue","vouch","vying","wacky","wafer","wager","waive","warty",
  "waver","waxen","weedy","welch","wench","whack","wharf","whelp","whiff","whiny",
  "whoop","wield","wight","willy","wimpy","wince","winch","wispy","wooer","wooly",
  "woozy","wordy","wrack","wrath","wreak","wrest","wring","wrung","wryly","yearn",
  "zesty","zonal",
];

/**
 * Tutte le risposte possibili, unite. Costruita dalle quattro fasce invece di
 * essere un quinto elenco scritto a parte: una parola aggiunta a una fascia
 * finisce qui da sola, e le due liste non possono divergere.
 */
export const ANSWER_WORDS: readonly string[] = [
  ...A1_A2_WORDS,
  ...B1_WORDS,
  ...B2_WORDS,
  ...C1_C2_WORDS,
];
